#!/usr/bin/env bash
# Assemble the three Mission Control dashboard plugins from one source tree.
#
#   hub      -> ~/.hermes/plugins/mission-control/          (owns every backend route)
#   waiting  -> ~/.hermes/plugins/mission-control-waiting/   (reuses the hub's API)
#   insights -> ~/.hermes/plugins/mission-control-insights/  (reuses the hub's API)
#
# One plugin = ONE nav tab (the manifest's `tab` is a single object, measured in
# hermes_cli/web_server_dashboard.py), so separate pages are separate plugin dirs; the bundles load
# no modules, so they share code by concatenation rather than by import.
#
# A page source file defines its component only — no IIFE, no register call:
#   src/pages/<page>.js  ->  header (SDK/React/h) + src/core.js + page + register footer
#
# Usage: ./build.sh   (idempotent; re-run after editing src/)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGINS_DIR="$(dirname "$HERE")"
PAGES="mission-control:overview mission-control-waiting:waiting mission-control-insights:insights"

build_one() {
  local name="$1" page="$2"
  local dir="$PLUGINS_DIR/$name"
  local label icon path position

  case "$page" in
    overview) label="Mission Control"; icon="Activity"; path="/mission-control"; position="after:kanban"
              tpl="manifest-hub.json"
              desc="One pane of glass over the estate: what every bot is running now, every board's state, the decisions waiting on Jesse (options plus the bot's recommendation, answerable in place), today's shipped work and the schedule." ;;
    waiting)  label="Waiting on Me";  icon="Clock";    path="/waiting-on-me";  position="after:mission-control"
              tpl="manifest.json"
              desc="Every decision parked on Jesse: the ask, the options, and the bot's recommendation — answerable in place, with the card id and a chat handoff on every row." ;;
    insights) label="Insights";       icon="BarChart3"; path="/insights";      position="after:waiting-on-me"
              tpl="manifest.json"
              desc="The estate at a glance: throughput, what state every card is in, what is stuck and for how long, who is working, what is failing, and schedule health." ;;
  esac

  mkdir -p "$dir/dashboard/dist"
  sed -e "s|@NAME@|$name|g" -e "s|@LABEL@|$label|g" -e "s|@ICON@|$icon|g" \
      -e "s|@PATH@|$path|g" -e "s|@POSITION@|$position|g" -e "s|@DESC@|$desc|g" \
      "$HERE/templates/$tpl" > "$dir/dashboard/manifest.json"

  {
    printf '/* %s — generated by build.sh from src/; edit src/ and re-run, do not edit this file. */\n' "$name"
    printf '(function () {\n  "use strict";\n\n'
    printf '  var SDK = window.__HERMES_PLUGIN_SDK__;\n'
    printf '  if (!SDK || !SDK.React) { console.error("%s: plugin SDK unavailable"); return; }\n' "$name"
    printf '  var React = SDK.React;\n'
    printf '  var h = React.createElement;\n'
    printf '  var useState = React.useState, useEffect = React.useEffect, useCallback = React.useCallback;\n'
    printf '  var fetchJSON = SDK.fetchJSON;\n'
    cat "$HERE/src/core.js"
    printf '\n/* ---- page: %s ---- */\n' "$page"
    cat "$HERE/src/pages/$page.js"
    printf '\n  window.__HERMES_PLUGINS__.register("%s", %sPage);\n' "$name" "$(echo "$page" | sed 's/^./\U&/')"
    printf '})();\n'
  } > "$dir/dashboard/dist/index.js"

  cp "$HERE/src/style.css" "$dir/dashboard/dist/style.css"

  if [ "$page" != "overview" ]; then
    sed -e "s|@NAME@|$name|g" -e "s|@LABEL@|$label|g" "$HERE/templates/plugin.yaml.tmpl" > "$dir/plugin.yaml"
    printf '"""%s — agent-side half of the plugin: deliberately empty.\n\nThe whole surface is the web-dashboard extension in ``dashboard/`` (a tab over the hub plugin'"'"'s\nread-only API). It registers no hooks, no tools and no CLI commands.\n"""\n\n\ndef register(ctx):  # noqa: ARG001 — plugin contract requires the entry point\n    """No-op registration: the dashboard extension needs no agent-side wiring."""\n' "$name" > "$dir/__init__.py"
  fi

  echo "built $name  ->  $dir/dashboard/dist/index.js ($(wc -c < "$dir/dashboard/dist/index.js") bytes)"
  node --check "$dir/dashboard/dist/index.js" && echo "  syntax ok"
}

for spec in $PAGES; do
  build_one "${spec%%:*}" "${spec##*:}"
done

echo
echo "Now: ensure every name is in plugins.enabled in ~/.hermes/config.yaml, rescan the plugin list,"
echo "and restart the dashboard (plugin_api.py routes mount at startup only)."
